version: '3.3'
services:
  
  app:
    build: .
  #   depends_on:
  #     - graph
  #     - elastic
  #     - mysql
  #     - redis
  
  # redis: 
  #   image: redis:5.0-rc4-alpine

  # graph:
  #   image: neo4j:3.4.7
  
  # elastic:
  #   image: elasticsearch:5.6.11-alpine
  
  # mysql:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql